version: 2

sources:
   - name: dev
     description: "Dev database"
     database: dev
     schema: dbt_venkatachaari
     freshness:
       warn_after: { count: 20, period: minute }
       error_after: { count: 40, period: minute }
     loaded_at_field: crt_ts
     tables:
       - name: customer
       - name: json_raw
       - name: dbt_audits
         columns:
           - name: crt_ts
