version: 2

sources:
   - name: dev
     description: "Dev database"
     database: dev
     schema: dbt_venkatachaari
     tables:
       - name: customer
       - name: json_raw
       - name: dbt_audits
         freshness:
           warn_after: { count: 20, period: minute }
           error_after: { count: 140, period: minute }
         loaded_at_field: "convert_timezone('America/Los_Angeles', 'UTC', crt_ts)"
         columns:
           - name: crt_ts
